# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greet.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bgreet.proto\x12\x04\x64\x65mo\"/\n\x08Greeting\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\"0\n\x0cGreetRequest\x12 \n\x08greeting\x18\x01 \x01(\x0b\x32\x0e.demo.Greeting\"\x1f\n\rGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x0cGreetService\x12\x32\n\x05Greet\x12\x12.demo.GreetRequest\x1a\x13.demo.GreetResponse\"\x00\x62\x06proto3')
)




_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='demo.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='demo.Greeting.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='demo.Greeting.lastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=68,
)


_GREETREQUEST = _descriptor.Descriptor(
  name='GreetRequest',
  full_name='demo.GreetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='demo.GreetRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=118,
)


_GREETRESPONSE = _descriptor.Descriptor(
  name='GreetResponse',
  full_name='demo.GreetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='demo.GreetResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=151,
)

_GREETREQUEST.fields_by_name['greeting'].message_type = _GREETING
DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
DESCRIPTOR.message_types_by_name['GreetRequest'] = _GREETREQUEST
DESCRIPTOR.message_types_by_name['GreetResponse'] = _GREETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:demo.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

GreetRequest = _reflection.GeneratedProtocolMessageType('GreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:demo.GreetRequest)
  })
_sym_db.RegisterMessage(GreetRequest)

GreetResponse = _reflection.GeneratedProtocolMessageType('GreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETRESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:demo.GreetResponse)
  })
_sym_db.RegisterMessage(GreetResponse)



_GREETSERVICE = _descriptor.ServiceDescriptor(
  name='GreetService',
  full_name='demo.GreetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=153,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greet',
    full_name='demo.GreetService.Greet',
    index=0,
    containing_service=None,
    input_type=_GREETREQUEST,
    output_type=_GREETRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETSERVICE)

DESCRIPTOR.services_by_name['GreetService'] = _GREETSERVICE

# @@protoc_insertion_point(module_scope)
