# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import movie_pb2 as movie__pb2


class MovieServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddMovie = channel.unary_unary(
        '/movie.MovieService/AddMovie',
        request_serializer=movie__pb2.Movie.SerializeToString,
        response_deserializer=movie__pb2.AddMovieResponse.FromString,
        )


class MovieServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddMovie(self, request, context):
    """unary API
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddMovie': grpc.unary_unary_rpc_method_handler(
          servicer.AddMovie,
          request_deserializer=movie__pb2.Movie.FromString,
          response_serializer=movie__pb2.AddMovieResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'movie.MovieService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
